### ISSUE TITLE
Not Generating the classes in any folder

### ISSUE THREAD

**Issue by alchemistgo87** [chiuki/gce2retrofit#1]
Hello,
When I use gce2retrofit plugin as described, it does not generate any retrofit classes. Where will it generate the classes?

Thank you.

**Comment by chiuki** [comment]
Did you have `discovery.json` in `src/main/gce2retrofit/subfolder`? (subfolder can be anything)

If so, the code will be generated in `build/generated/source/gce2retrofit/`

**Comment by alchemistgo87** [comment]
Yes, that's correct, it was generated in the build/generated/source/gce2retrofit/ folder. Thanks a lot Chiuki. This seems to be a very userful plugin.

I have few more queries for you:
1) How would we make an authenticated call using retrofit, which can normally be done using httprequest builder and setting the credentials inside. Can you provide some sample code.

2) How apt is Google cloud endpoint for creating a large scale social media app. Are there any good tutorials or samples.

3) Since gce/gae does not provide authentication using id other than gmail id, is there any solution/substitute for this.
(Last question is quite out of context, but I feel that you can guide me very well since you have a great experience of working with google technologies. Thanks in advance.)

**Comment by chiuki** [comment]
I've added the code generation directory to README.md

Won't be addressing the other questions since they are out of scope for this project.
