### ISSUE TITLE
NPE with nested "resources" 

### ISSUE THREAD

**Issue by krishan711** [chiuki/gce2retrofit#3]
Hey there! Thanks for this great project. I'm having a bit of a problem though. I finally managed to figure out whats going wrong:

some of my apis are declared like so:

```
@appapi.api_class(resource_name='base.first', path='base/first')
```

(this is the api declaration on the class rather than the method (I have a multi-class api)

this generates a discovery doc where the 'resources' section looks like this:

```
 "resources": {
  "base": {
   "resources": {
    "first": {
     "methods": {
      "add": {
       "id": "base.first.method_name",
       "path": "base/first/method_name",
       "httpMethod": "POST",
       "description": "",
       "request": {
        "$ref": "requestClass",
        "parameterName": "resource"
       },
       "response": {
        "$ref": "responseClass"
       },
       "scopes": [
        "https://www.googleapis.com/auth/userinfo.email"
       ]
      }
     }
    }
   }
  }
 }
```

As you can see, there is a resources json nested under the main one. If I remove the nested-ness of this the issue doesn't appear.

Please let me know if I can provide more details. I've manually obfuscated the method names and other stuff since I have very little security on the backend at the moment :disappointed:

**Comment by chiuki** [comment]
Please provide the discovery file, or at least post a snippet of the problematic part.

**Comment by krishan711** [comment]
Hey sorry, I pressed enter after entering the title and it submitted it. I've updated the description above. I'll take a look at the code to see if I can push a fix :)

**Comment by chiuki** [comment]
Great!

I just made a commit that takes care of the case when "methods" is at top level (i.e. not under "resources"), so you can do something similar.

If you have a fix, please add a test as well. Thanks!

**Comment by krishan711** [comment]
I just realised I have no idea how to test this locally, but I will push the fix I think will do the job now :)

**Comment by chiuki** [comment]
The easiest way is to add a new test case. I've added some instructions here:
https://github.com/chiuki/gce2retrofit/blob/master/CONTRIBUTING.md

You can also push the gradle plugin to the build directory: When you do `./gradlew gce2retrofit:uploadArchives`, the `sample-java` and `sample-android` projects will use the local repo compiled at `gce2retrofit/build/repo`. But `uploadArchives` takes a while to run so developing via `./gradlew gce2retrofit:test` is faster and easier.

**Comment by krishan711** [comment]
Ah brilliant, thanks. Almost done with it, will push in a bit :+1:
