### ISSUE TITLE
How to set GoogleAccountCredential in restadapter

### ISSUE THREAD

**Issue by alchemistgo87** [chiuki/gce2retrofit#7]
While creating retrofit restadapter in android how can we set GoogleAccountCredential for authorization .

**Comment by chiuki** [comment]
Sorry out of scope for this project.

**Comment by alchemistgo87** [comment]
If possible can u email me the solution please, It would be a great help for me.
(My email id is: anshul.go87@gmail.com)
Thanks in anticipation.
