### ISSUE TITLE
 NullPointerException when generating retrofit classes

### ISSUE THREAD

**Issue by thib-rdr** [chiuki/gce2retrofit#9]
Hi, new development regarding the first issue I reported (#2).

I have a NullPointerException while generating from a discovery. I placed the discovery here : 

http://0bin.net/paste/zOLyoDxDFWVCBKi9#wuCrnlduckVGDaNhOhfCAkcynDPFKKWQDfkavy5FlZd

Here is the object gce2retrofit is trying to convert : 

http://0bin.net/paste/u+YHjIYgX8XTXej+#8IXu-jbDy5OnifCQKIUuCgHjKU+VnR/xBUVfnXjEjPg

Thanks,

**Comment by chiuki** [comment]
I have a fix for the `NullPointerException`, but the rest of the discovery file you pasted has a different format from what I'm expecting. For instance, I don't see `allowGet` in the GCE discovery description: 
https://developers.google.com/discovery/v1/reference/apis

How did you generate this discovery file?

**Comment by chiuki** [comment]
I looked at https://kyadev-kfkb.appspot.com/_ah/api/discovery/v1/apis/acl/v1/rest and don't see  `allowGet` etc. Closing this issue since the `NullPointerException` has been fixed.
